       SUBROUTINE VPASSI(A,B,NFFT,MSKIP,ISKIP2,NUMBER,ISIGN)
C
C      WRITTEN JULY 24, 1992 BY NORMAN J. TROULLIER JR.
C      COPYRIGHT NORMAN J. TROULLIER JR.
C      DISTRIBUTION ONLY BY WRITTEN PERMISSION
C      NOTE: *vdir nodep ARE NEC-SX3 DIRECTIVES
C
       IMPLICIT REAL*8 (A-H,O-Z)
C
       DIMENSION A(*),B(*)
C
       PARAMETER (SIN60=0.8660254037844386D0)
       PARAMETER (SIN72=0.9510565162951536D0)
       PARAMETER (SIN36=0.5877852522924732D0)
       PARAMETER (SQ54=0.5590169943749475D0)
       PARAMETER (PO25=0.25D0)
       PARAMETER (SQ2=0.7071067811865476D0)
       PARAMETER (PO5=0.5D0)
       PARAMETER (SIN20=0.3420201433256687D0)
       PARAMETER (SIN40=0.6427876096865393D0)
       PARAMETER (SIN80=0.9848077530122080D0)
       PARAMETER (COS20=0.9396926207859083D0)
       PARAMETER (COS40=0.7660444431189781D0)
       PARAMETER (COS80=0.1736481776669304D0)
       PARAMETER (COS36=0.8090169943749475D0)
       PARAMETER (COS72=0.3090169943749475D0)
C
       IB=MSKIP
C
       IF(NFFT .EQ. 10) THEN
C
C        FACTOR 10
C
         IC=IB+MSKIP
         ID=IC+MSKIP
         IE=ID+MSKIP
         IF=IE+MSKIP
         IG=IF+MSKIP
         IH=IG+MSKIP
         II=IH+MSKIP
         IJ=II+MSKIP
         IF(ISIGN.LT.0) THEN
           IADD1=-ISKIP2+1
*vdir nodep             
CDIR$ IVDEP
CDEC$ IVDEP
           DO NU=1,NUMBER
             IADD1=IADD1+ISKIP2
             T1REAL=A(IADD1)+A(IADD1+IF)
             T1IMAG=B(IADD1)+B(IADD1+IF)
             T2REAL=A(IADD1)-A(IADD1+IF)
             T2IMAG=B(IADD1)-B(IADD1+IF)
             T3REAL=A(IADD1+IB)+A(IADD1+IG)
             T3IMAG=B(IADD1+IB)+B(IADD1+IG)
             T4REAL=A(IADD1+IB)-A(IADD1+IG)
             T4IMAG=B(IADD1+IB)-B(IADD1+IG)
             T5REAL=A(IADD1+IC)+A(IADD1+IH)
             T5IMAG=B(IADD1+IC)+B(IADD1+IH)
             T6REAL=A(IADD1+IC)-A(IADD1+IH)
             T6IMAG=B(IADD1+IC)-B(IADD1+IH)
             T7REAL=A(IADD1+ID)+A(IADD1+II)
             T7IMAG=B(IADD1+ID)+B(IADD1+II)
             T8REAL=A(IADD1+ID)-A(IADD1+II)
             T8IMAG=B(IADD1+ID)-B(IADD1+II)
             T9REAL=A(IADD1+IE)+A(IADD1+IJ)
             T9IMAG=B(IADD1+IE)+B(IADD1+IJ)
             T10REAL=A(IADD1+IE)-A(IADD1+IJ)
             T10IMAG=B(IADD1+IE)-B(IADD1+IJ)
             B1REAL=T3REAL+T9REAL
             B1IMAG=T3IMAG+T9IMAG
             B2REAL=T3REAL-T9REAL
             B2IMAG=T3IMAG-T9IMAG
             B3REAL=T5REAL+T7REAL
             B3IMAG=T5IMAG+T7IMAG
             B4REAL=T5REAL-T7REAL
             B4IMAG=T5IMAG-T7IMAG
             B5REAL=T4REAL+T10REAL
             B5IMAG=T4IMAG+T10IMAG
             B6REAL=T4REAL-T10REAL
             B6IMAG=T4IMAG-T10IMAG
             B7REAL=T6REAL+T8REAL
             B7IMAG=T6IMAG+T8IMAG
             B8REAL=T6REAL-T8REAL
             B8IMAG=T6IMAG-T8IMAG
             C1REAL=T2REAL+B6REAL*COS36+B8REAL*COS72
             C1IMAG=T2IMAG+B6IMAG*COS36+B8IMAG*COS72
             C2REAL=B5REAL*SIN36+B7REAL*SIN72
             C2IMAG=B5IMAG*SIN36+B7IMAG*SIN72
             C3REAL=T1REAL+B1REAL*COS72-B3REAL*COS36
             C3IMAG=T1IMAG+B1IMAG*COS72-B3IMAG*COS36
             C4REAL=B2REAL*SIN72+B4REAL*SIN36
             C4IMAG=B2IMAG*SIN72+B4IMAG*SIN36
             C5REAL=T2REAL-B6REAL*COS72-B8REAL*COS36
             C5IMAG=T2IMAG-B6IMAG*COS72-B8IMAG*COS36
             C6REAL=B5REAL*SIN72-B7REAL*SIN36
             C6IMAG=B5IMAG*SIN72-B7IMAG*SIN36
             C7REAL=T1REAL-B1REAL*COS36+B3REAL*COS72
             C7IMAG=T1IMAG-B1IMAG*COS36+B3IMAG*COS72
             C8REAL=B2REAL*SIN36-B4REAL*SIN72
             C8IMAG=B2IMAG*SIN36-B4IMAG*SIN72
             A(IADD1)   =T1REAL+B1REAL+B3REAL
             B(IADD1)   =T1IMAG+B1IMAG+B3IMAG
             A(IADD1+IB)=C1REAL-C2IMAG
             B(IADD1+IB)=C1IMAG+C2REAL
             A(IADD1+IC)=C3REAL-C4IMAG
             B(IADD1+IC)=C3IMAG+C4REAL
             A(IADD1+ID)=C5REAL-C6IMAG
             B(IADD1+ID)=C5IMAG+C6REAL
             A(IADD1+IE)=C7REAL-C8IMAG
             B(IADD1+IE)=C7IMAG+C8REAL
             A(IADD1+IF)=T2REAL-B6REAL+B8REAL
             B(IADD1+IF)=T2IMAG-B6IMAG+B8IMAG
             A(IADD1+IG)=C7REAL+C8IMAG
             B(IADD1+IG)=C7IMAG-C8REAL
             A(IADD1+IH)=C5REAL+C6IMAG
             B(IADD1+IH)=C5IMAG-C6REAL
             A(IADD1+II)=C3REAL+C4IMAG
             B(IADD1+II)=C3IMAG-C4REAL
             A(IADD1+IJ)=C1REAL+C2IMAG
             B(IADD1+IJ)=C1IMAG-C2REAL
           ENDDO
         ELSE
           IADD1=-ISKIP2+1
*vdir nodep             
CDIR$ IVDEP
CDEC$ IVDEP
           DO NU=1,NUMBER
             IADD1=IADD1+ISKIP2
             T1REAL=A(IADD1)+A(IADD1+IF)
             T1IMAG=B(IADD1)+B(IADD1+IF)
             T2REAL=A(IADD1)-A(IADD1+IF)
             T2IMAG=B(IADD1)-B(IADD1+IF)
             T3REAL=A(IADD1+IB)+A(IADD1+IG)
             T3IMAG=B(IADD1+IB)+B(IADD1+IG)
             T4REAL=A(IADD1+IB)-A(IADD1+IG)
             T4IMAG=B(IADD1+IB)-B(IADD1+IG)
             T5REAL=A(IADD1+IC)+A(IADD1+IH)
             T5IMAG=B(IADD1+IC)+B(IADD1+IH)
             T6REAL=A(IADD1+IC)-A(IADD1+IH)
             T6IMAG=B(IADD1+IC)-B(IADD1+IH)
             T7REAL=A(IADD1+ID)+A(IADD1+II)
             T7IMAG=B(IADD1+ID)+B(IADD1+II)
             T8REAL=A(IADD1+ID)-A(IADD1+II)
             T8IMAG=B(IADD1+ID)-B(IADD1+II)
             T9REAL=A(IADD1+IE)+A(IADD1+IJ)
             T9IMAG=B(IADD1+IE)+B(IADD1+IJ)
             T10REAL=A(IADD1+IE)-A(IADD1+IJ)
             T10IMAG=B(IADD1+IE)-B(IADD1+IJ)
             B1REAL=T3REAL+T9REAL
             B1IMAG=T3IMAG+T9IMAG
             B2REAL=T3REAL-T9REAL
             B2IMAG=T3IMAG-T9IMAG
             B3REAL=T5REAL+T7REAL
             B3IMAG=T5IMAG+T7IMAG
             B4REAL=T5REAL-T7REAL
             B4IMAG=T5IMAG-T7IMAG
             B5REAL=T4REAL+T10REAL
             B5IMAG=T4IMAG+T10IMAG
             B6REAL=T4REAL-T10REAL
             B6IMAG=T4IMAG-T10IMAG
             B7REAL=T6REAL+T8REAL
             B7IMAG=T6IMAG+T8IMAG
             B8REAL=T6REAL-T8REAL
             B8IMAG=T6IMAG-T8IMAG
             C1REAL=T2REAL+B6REAL*COS36+B8REAL*COS72
             C1IMAG=T2IMAG+B6IMAG*COS36+B8IMAG*COS72
             C2REAL=B5REAL*SIN36+B7REAL*SIN72
             C2IMAG=B5IMAG*SIN36+B7IMAG*SIN72
             C3REAL=T1REAL+B1REAL*COS72-B3REAL*COS36
             C3IMAG=T1IMAG+B1IMAG*COS72-B3IMAG*COS36
             C4REAL=B2REAL*SIN72+B4REAL*SIN36
             C4IMAG=B2IMAG*SIN72+B4IMAG*SIN36
             C5REAL=T2REAL-B6REAL*COS72-B8REAL*COS36
             C5IMAG=T2IMAG-B6IMAG*COS72-B8IMAG*COS36
             C6REAL=B5REAL*SIN72-B7REAL*SIN36
             C6IMAG=B5IMAG*SIN72-B7IMAG*SIN36
             C7REAL=T1REAL-B1REAL*COS36+B3REAL*COS72
             C7IMAG=T1IMAG-B1IMAG*COS36+B3IMAG*COS72
             C8REAL=B2REAL*SIN36-B4REAL*SIN72
             C8IMAG=B2IMAG*SIN36-B4IMAG*SIN72
             A(IADD1)   =T1REAL+B1REAL+B3REAL
             B(IADD1)   =T1IMAG+B1IMAG+B3IMAG
             A(IADD1+IB)=C1REAL+C2IMAG
             B(IADD1+IB)=C1IMAG-C2REAL
             A(IADD1+IC)=C3REAL+C4IMAG
             B(IADD1+IC)=C3IMAG-C4REAL
             A(IADD1+ID)=C5REAL+C6IMAG
             B(IADD1+ID)=C5IMAG-C6REAL
             A(IADD1+IE)=C7REAL+C8IMAG
             B(IADD1+IE)=C7IMAG-C8REAL
             A(IADD1+IF)=T2REAL-B6REAL+B8REAL
             B(IADD1+IF)=T2IMAG-B6IMAG+B8IMAG
             A(IADD1+IG)=C7REAL-C8IMAG
             B(IADD1+IG)=C7IMAG+C8REAL
             A(IADD1+IH)=C5REAL-C6IMAG
             B(IADD1+IH)=C5IMAG+C6REAL
             A(IADD1+II)=C3REAL-C4IMAG
             B(IADD1+II)=C3IMAG+C4REAL
             A(IADD1+IJ)=C1REAL-C2IMAG
             B(IADD1+IJ)=C1IMAG+C2REAL
           ENDDO
         ENDIF
       ELSEIF(NFFT .EQ.  9) THEN
C
C        FACTOR 9
C
         IC=IB+MSKIP
         ID=IC+MSKIP
         IE=ID+MSKIP
         IF=IE+MSKIP
         IG=IF+MSKIP
         IH=IG+MSKIP
         II=IH+MSKIP
         IF(ISIGN.LT.0) THEN
           IADD1=-ISKIP2+1
*vdir nodep             
CDIR$ IVDEP
CDEC$ IVDEP
           DO NU=1,NUMBER
             IADD1=IADD1+ISKIP2
             T1REAL=A(IADD1+IB)+A(IADD1+II)
             T1IMAG=B(IADD1+IB)+B(IADD1+II)
             T2REAL=A(IADD1+IB)-A(IADD1+II)
             T2IMAG=B(IADD1+IB)-B(IADD1+II)
             T3REAL=A(IADD1+IC)+A(IADD1+IH)
             T3IMAG=B(IADD1+IC)+B(IADD1+IH)
             T4REAL=A(IADD1+IC)-A(IADD1+IH)
             T4IMAG=B(IADD1+IC)-B(IADD1+IH)
             T5REAL=A(IADD1+ID)+A(IADD1+IG)
             T5IMAG=B(IADD1+ID)+B(IADD1+IG)
             T6REAL=A(IADD1+ID)-A(IADD1+IG)
             T6IMAG=B(IADD1+ID)-B(IADD1+IG)
             T7REAL=A(IADD1+IE)+A(IADD1+IF)
             T7IMAG=B(IADD1+IE)+B(IADD1+IF)
             T8REAL=A(IADD1+IE)-A(IADD1+IF)
             T8IMAG=B(IADD1+IE)-B(IADD1+IF)
             B1REAL=A(IADD1)+T5REAL
             B1IMAG=B(IADD1)+T5IMAG
             B2REAL=T1REAL+T3REAL+T7REAL
             B2IMAG=T1IMAG+T3IMAG+T7IMAG
             B3REAL=B1REAL-PO5*B2REAL
             B3IMAG=B1IMAG-PO5*B2IMAG
             B4REAL=(T2REAL-T4REAL+T8REAL)*SIN60
             B4IMAG=(T2IMAG-T4IMAG+T8IMAG)*SIN60
             B5REAL=-PO5*T5REAL+A(IADD1)
             B5IMAG=-PO5*T5IMAG+B(IADD1)
             B6REAL=T6REAL*SIN60
             B6IMAG=T6IMAG*SIN60
             B7REAL=T1REAL*COS40+T3REAL*COS80+B5REAL-T7REAL*COS20
             B7IMAG=T1IMAG*COS40+T3IMAG*COS80+B5IMAG-T7IMAG*COS20
             B8REAL=T2REAL*SIN40+T4REAL*SIN80+B6REAL+T8REAL*SIN20
             B8IMAG=T2IMAG*SIN40+T4IMAG*SIN80+B6IMAG+T8IMAG*SIN20
             B9REAL=T1REAL*COS80-T3REAL*COS20+B5REAL+T7REAL*COS40
             B9IMAG=T1IMAG*COS80-T3IMAG*COS20+B5IMAG+T7IMAG*COS40
             B10REAL=T2REAL*SIN80+T4REAL*SIN20-B6REAL-T8REAL*SIN40
             B10IMAG=T2IMAG*SIN80+T4IMAG*SIN20-B6IMAG-T8IMAG*SIN40
             B11REAL=-T1REAL*COS20+T3REAL*COS40+B5REAL+T7REAL*COS80
             B11IMAG=-T1IMAG*COS20+T3IMAG*COS40+B5IMAG+T7IMAG*COS80
             B12REAL=T2REAL*SIN20-T4REAL*SIN40+B6REAL-T8REAL*SIN80
             B12IMAG=T2IMAG*SIN20-T4IMAG*SIN40+B6IMAG-T8IMAG*SIN80
             A(IADD1)   =B1REAL+B2REAL
             B(IADD1)   =B1IMAG+B2IMAG
             A(IADD1+IB)=B7REAL-B8IMAG
             B(IADD1+IB)=B7IMAG+B8REAL
             A(IADD1+IC)=B9REAL-B10IMAG
             B(IADD1+IC)=B9IMAG+B10REAL
             A(IADD1+ID)=B3REAL-B4IMAG
             B(IADD1+ID)=B3IMAG+B4REAL
             A(IADD1+IE)=B11REAL-B12IMAG
             B(IADD1+IE)=B11IMAG+B12REAL
             A(IADD1+IF)=B11REAL+B12IMAG
             B(IADD1+IF)=B11IMAG-B12REAL
             A(IADD1+IG)=B3REAL+B4IMAG
             B(IADD1+IG)=B3IMAG-B4REAL
             A(IADD1+IH)=B9REAL+B10IMAG
             B(IADD1+IH)=B9IMAG-B10REAL
             A(IADD1+II)=B7REAL+B8IMAG
             B(IADD1+II)=B7IMAG-B8REAL 
           ENDDO
         ELSE
           IADD1=-ISKIP2+1
*vdir nodep             
CDIR$ IVDEP
CDEC$ IVDEP
           DO NU=1,NUMBER
             IADD1=IADD1+ISKIP2
             T1REAL=A(IADD1+IB)+A(IADD1+II)
             T1IMAG=B(IADD1+IB)+B(IADD1+II)
             T2REAL=A(IADD1+IB)-A(IADD1+II)
             T2IMAG=B(IADD1+IB)-B(IADD1+II)
             T3REAL=A(IADD1+IC)+A(IADD1+IH)
             T3IMAG=B(IADD1+IC)+B(IADD1+IH)
             T4REAL=A(IADD1+IC)-A(IADD1+IH)
             T4IMAG=B(IADD1+IC)-B(IADD1+IH)
             T5REAL=A(IADD1+ID)+A(IADD1+IG)
             T5IMAG=B(IADD1+ID)+B(IADD1+IG)
             T6REAL=A(IADD1+ID)-A(IADD1+IG)
             T6IMAG=B(IADD1+ID)-B(IADD1+IG)
             T7REAL=A(IADD1+IE)+A(IADD1+IF)
             T7IMAG=B(IADD1+IE)+B(IADD1+IF)
             T8REAL=A(IADD1+IE)-A(IADD1+IF)
             T8IMAG=B(IADD1+IE)-B(IADD1+IF)
             B1REAL=A(IADD1)+T5REAL
             B1IMAG=B(IADD1)+T5IMAG
             B2REAL=T1REAL+T3REAL+T7REAL
             B2IMAG=T1IMAG+T3IMAG+T7IMAG
             B3REAL=B1REAL-PO5*B2REAL
             B3IMAG=B1IMAG-PO5*B2IMAG
             B4REAL=(T2REAL-T4REAL+T8REAL)*SIN60
             B4IMAG=(T2IMAG-T4IMAG+T8IMAG)*SIN60
             B5REAL=-PO5*T5REAL+A(IADD1)
             B5IMAG=-PO5*T5IMAG+B(IADD1)
             B6REAL=T6REAL*SIN60
             B6IMAG=T6IMAG*SIN60
             B7REAL=T1REAL*COS40+T3REAL*COS80+B5REAL-T7REAL*COS20
             B7IMAG=T1IMAG*COS40+T3IMAG*COS80+B5IMAG-T7IMAG*COS20
             B8REAL=T2REAL*SIN40+T4REAL*SIN80+B6REAL+T8REAL*SIN20
             B8IMAG=T2IMAG*SIN40+T4IMAG*SIN80+B6IMAG+T8IMAG*SIN20
             B9REAL=T1REAL*COS80-T3REAL*COS20+B5REAL+T7REAL*COS40
             B9IMAG=T1IMAG*COS80-T3IMAG*COS20+B5IMAG+T7IMAG*COS40
             B10REAL=T2REAL*SIN80+T4REAL*SIN20-B6REAL-T8REAL*SIN40
             B10IMAG=T2IMAG*SIN80+T4IMAG*SIN20-B6IMAG-T8IMAG*SIN40
             B11REAL=-T1REAL*COS20+T3REAL*COS40+B5REAL+T7REAL*COS80
             B11IMAG=-T1IMAG*COS20+T3IMAG*COS40+B5IMAG+T7IMAG*COS80
             B12REAL=T2REAL*SIN20-T4REAL*SIN40+B6REAL-T8REAL*SIN80
             B12IMAG=T2IMAG*SIN20-T4IMAG*SIN40+B6IMAG-T8IMAG*SIN80
             A(IADD1)   =B1REAL+B2REAL
             B(IADD1)   =B1IMAG+B2IMAG
             A(IADD1+IB)=B7REAL+B8IMAG
             B(IADD1+IB)=B7IMAG-B8REAL
             A(IADD1+IC)=B9REAL+B10IMAG
             B(IADD1+IC)=B9IMAG-B10REAL
             A(IADD1+ID)=B3REAL+B4IMAG
             B(IADD1+ID)=B3IMAG-B4REAL
             A(IADD1+IE)=B11REAL+B12IMAG
             B(IADD1+IE)=B11IMAG-B12REAL
             A(IADD1+IF)=B11REAL-B12IMAG
             B(IADD1+IF)=B11IMAG+B12REAL
             A(IADD1+IG)=B3REAL-B4IMAG
             B(IADD1+IG)=B3IMAG+B4REAL
             A(IADD1+IH)=B9REAL-B10IMAG
             B(IADD1+IH)=B9IMAG+B10REAL
             A(IADD1+II)=B7REAL-B8IMAG
             B(IADD1+II)=B7IMAG+B8REAL 
           ENDDO
         ENDIF
       ELSEIF (NFFT .EQ. 8) THEN
C
C        FACTOR 8
C
         IC=IB+MSKIP
         ID=IC+MSKIP
         IE=ID+MSKIP
         IF=IE+MSKIP
         IG=IF+MSKIP
         IH=IG+MSKIP
         IF(ISIGN.LT.0) THEN
           IADD1=-ISKIP2+1
*vdir nodep             
CDIR$ IVDEP
CDEC$ IVDEP
           DO NU=1,NUMBER
             IADD1=IADD1+ISKIP2
             T1REAL=A(IADD1)+A(IADD1+IE)
             T1IMAG=B(IADD1)+B(IADD1+IE)
             T2REAL=A(IADD1)-A(IADD1+IE)
             T2IMAG=B(IADD1)-B(IADD1+IE)
             T3REAL=A(IADD1+IB)+A(IADD1+IF)
             T3IMAG=B(IADD1+IB)+B(IADD1+IF)
             T4REAL=A(IADD1+IB)-A(IADD1+IF)
             T4IMAG=B(IADD1+IB)-B(IADD1+IF)
             T5REAL=A(IADD1+IC)+A(IADD1+IG)
             T5IMAG=B(IADD1+IC)+B(IADD1+IG)
             T6REAL=A(IADD1+IC)-A(IADD1+IG)
             T6IMAG=B(IADD1+IC)-B(IADD1+IG)
             T7REAL=A(IADD1+ID)+A(IADD1+IH)
             T7IMAG=B(IADD1+ID)+B(IADD1+IH)
             T8REAL=A(IADD1+ID)-A(IADD1+IH)
             T8IMAG=B(IADD1+ID)-B(IADD1+IH)
             B1REAL=T1REAL+T5REAL
             B1IMAG=T1IMAG+T5IMAG
             B2REAL=T1REAL-T5REAL
             B2IMAG=T1IMAG-T5IMAG
             B3REAL=T3REAL+T7REAL
             B3IMAG=T3IMAG+T7IMAG
             B4REAL=T7IMAG-T3IMAG
             B4IMAG=T3REAL-T7REAL
             B5REAL=T2REAL-T6IMAG
             B5IMAG=T2IMAG+T6REAL
             B6REAL=T2REAL+T6IMAG
             B6IMAG=T2IMAG-T6REAL
             T1    =SQ2*(T4REAL+T4IMAG)
             T2    =SQ2*(T4REAL-T4IMAG)
             T3    =SQ2*(T8REAL+T8IMAG)
             T4    =SQ2*(T8REAL-T8IMAG)
             B7REAL=T2-T3
             B7IMAG=T1+T4
             B8REAL=T1-T4
             B8IMAG=-(T2+T3)
             A(IADD1)   =B1REAL+B3REAL
             B(IADD1)   =B1IMAG+B3IMAG
             A(IADD1+IB)=B5REAL+B7REAL
             B(IADD1+IB)=B5IMAG+B7IMAG
             A(IADD1+IC)=B2REAL+B4REAL
             B(IADD1+IC)=B2IMAG+B4IMAG
             A(IADD1+ID)=B6REAL-B8REAL
             B(IADD1+ID)=B6IMAG-B8IMAG
             A(IADD1+IE)=B1REAL-B3REAL
             B(IADD1+IE)=B1IMAG-B3IMAG
             A(IADD1+IF)=B5REAL-B7REAL
             B(IADD1+IF)=B5IMAG-B7IMAG
             A(IADD1+IG)=B2REAL-B4REAL
             B(IADD1+IG)=B2IMAG-B4IMAG
             A(IADD1+IH)=B6REAL+B8REAL
             B(IADD1+IH)=B6IMAG+B8IMAG
           ENDDO
         ELSE
           IADD1=-ISKIP2+1
*vdir nodep             
CDIR$ IVDEP
CDEC$ IVDEP
           DO NU=1,NUMBER
             IADD1=IADD1+ISKIP2
             T1REAL=A(IADD1)+A(IADD1+IE)
             T1IMAG=B(IADD1)+B(IADD1+IE)
             T2REAL=A(IADD1)-A(IADD1+IE)
             T2IMAG=B(IADD1)-B(IADD1+IE)
             T3REAL=A(IADD1+IB)+A(IADD1+IF)
             T3IMAG=B(IADD1+IB)+B(IADD1+IF)
             T4REAL=A(IADD1+IB)-A(IADD1+IF)
             T4IMAG=B(IADD1+IB)-B(IADD1+IF)
             T5REAL=A(IADD1+IC)+A(IADD1+IG)
             T5IMAG=B(IADD1+IC)+B(IADD1+IG)
             T6REAL=A(IADD1+IC)-A(IADD1+IG)
             T6IMAG=B(IADD1+IC)-B(IADD1+IG)
             T7REAL=A(IADD1+ID)+A(IADD1+IH)
             T7IMAG=B(IADD1+ID)+B(IADD1+IH)
             T8REAL=A(IADD1+ID)-A(IADD1+IH)
             T8IMAG=B(IADD1+ID)-B(IADD1+IH)
             B1REAL=T1REAL+T5REAL
             B1IMAG=T1IMAG+T5IMAG
             B2REAL=T1REAL-T5REAL
             B2IMAG=T1IMAG-T5IMAG
             B3REAL=T3REAL+T7REAL
             B3IMAG=T3IMAG+T7IMAG
             B4REAL=T7IMAG-T3IMAG
             B4IMAG=T3REAL-T7REAL
             B5REAL=T2REAL-T6IMAG
             B5IMAG=T2IMAG+T6REAL
             B6REAL=T2REAL+T6IMAG
             B6IMAG=T2IMAG-T6REAL
             T1    =SQ2*(T4REAL+T4IMAG)
             T2    =SQ2*(T4REAL-T4IMAG)
             T3    =SQ2*(T8REAL+T8IMAG)
             T4    =SQ2*(T8REAL-T8IMAG)
             B7REAL=T2-T3
             B7IMAG=T1+T4
             B8REAL=T1-T4
             B8IMAG=-(T2+T3)
             A(IADD1)   =B1REAL+B3REAL
             B(IADD1)   =B1IMAG+B3IMAG
             A(IADD1+IB)=B6REAL+B8REAL
             B(IADD1+IB)=B6IMAG+B8IMAG
             A(IADD1+IC)=B2REAL-B4REAL
             B(IADD1+IC)=B2IMAG-B4IMAG
             A(IADD1+ID)=B5REAL-B7REAL
             B(IADD1+ID)=B5IMAG-B7IMAG
             A(IADD1+IE)=B1REAL-B3REAL
             B(IADD1+IE)=B1IMAG-B3IMAG
             A(IADD1+IF)=B6REAL-B8REAL
             B(IADD1+IF)=B6IMAG-B8IMAG
             A(IADD1+IG)=B2REAL+B4REAL
             B(IADD1+IG)=B2IMAG+B4IMAG
             A(IADD1+IH)=B5REAL+B7REAL
             B(IADD1+IH)=B5IMAG+B7IMAG
           ENDDO
         ENDIF
       ELSEIF (NFFT .EQ. 6) THEN
C
C        FACTOR 6
C
         IC=IB+MSKIP
         ID=IC+MSKIP
         IE=ID+MSKIP
         IF=IE+MSKIP
         IF(ISIGN.LT.0) THEN
           IADD1=-ISKIP2+1
*vdir nodep             
CDIR$ IVDEP
CDEC$ IVDEP
           DO NU=1,NUMBER
             IADD1=IADD1+ISKIP2
             T1REAL=A(IADD1)+A(IADD1+ID)
             T1IMAG=B(IADD1)+B(IADD1+ID)
             T2REAL=A(IADD1)-A(IADD1+ID)
             T2IMAG=B(IADD1)-B(IADD1+ID)
             T3REAL=A(IADD1+IB)+A(IADD1+IE)
             T3IMAG=B(IADD1+IB)+B(IADD1+IE)
             T4REAL=A(IADD1+IB)-A(IADD1+IE)
             T4IMAG=B(IADD1+IB)-B(IADD1+IE)
             T5REAL=A(IADD1+IC)+A(IADD1+IF)
             T5IMAG=B(IADD1+IC)+B(IADD1+IF)
             T6REAL=A(IADD1+IC)-A(IADD1+IF)
             T6IMAG=B(IADD1+IC)-B(IADD1+IF)
             B1REAL=T3REAL+T5REAL
             B1IMAG=T3IMAG+T5IMAG
             B1REAL5=PO5*B1REAL
             B1IMAG5=PO5*B1IMAG
             B2REAL=(T3REAL-T5REAL)*SIN60
             B2IMAG=(T3IMAG-T5IMAG)*SIN60
             B3REAL=T4REAL-T6REAL
             B3IMAG=T4IMAG-T6IMAG
             B3REAL5=PO5*B3REAL
             B3IMAG5=PO5*B3IMAG
             B4REAL=(T4REAL+T6REAL)*SIN60
             B4IMAG=(T4IMAG+T6IMAG)*SIN60
             A(IADD1)   =T1REAL+B1REAL
             B(IADD1)   =T1IMAG+B1IMAG
             A(IADD1+IB)=T2REAL+B3REAL5-B4IMAG
             B(IADD1+IB)=T2IMAG+B3IMAG5+B4REAL
             A(IADD1+IC)=T1REAL-B1REAL5-B2IMAG
             B(IADD1+IC)=T1IMAG-B1IMAG5+B2REAL
             A(IADD1+ID)=T2REAL-B3REAL
             B(IADD1+ID)=T2IMAG-B3IMAG
             A(IADD1+IE)=T1REAL-B1REAL5+B2IMAG
             B(IADD1+IE)=T1IMAG-B1IMAG5-B2REAL
             A(IADD1+IF)=T2REAL+B3REAL5+B4IMAG
             B(IADD1+IF)=T2IMAG+B3IMAG5-B4REAL
           ENDDO
         ELSE
           IADD1=-ISKIP2+1
*vdir nodep             
CDIR$ IVDEP
CDEC$ IVDEP
           DO NU=1,NUMBER
             IADD1=IADD1+ISKIP2
             T1REAL=A(IADD1)+A(IADD1+ID)
             T1IMAG=B(IADD1)+B(IADD1+ID)
             T2REAL=A(IADD1)-A(IADD1+ID)
             T2IMAG=B(IADD1)-B(IADD1+ID)
             T3REAL=A(IADD1+IB)+A(IADD1+IE)
             T3IMAG=B(IADD1+IB)+B(IADD1+IE)
             T4REAL=A(IADD1+IB)-A(IADD1+IE)
             T4IMAG=B(IADD1+IB)-B(IADD1+IE)
             T5REAL=A(IADD1+IC)+A(IADD1+IF)
             T5IMAG=B(IADD1+IC)+B(IADD1+IF)
             T6REAL=A(IADD1+IC)-A(IADD1+IF)
             T6IMAG=B(IADD1+IC)-B(IADD1+IF)
             B1REAL=T3REAL+T5REAL
             B1IMAG=T3IMAG+T5IMAG
             B1REAL5=PO5*B1REAL
             B1IMAG5=PO5*B1IMAG
             B2REAL=(T3REAL-T5REAL)*SIN60
             B2IMAG=(T3IMAG-T5IMAG)*SIN60
             B3REAL=T4REAL-T6REAL
             B3IMAG=T4IMAG-T6IMAG
             B3REAL5=PO5*B3REAL
             B3IMAG5=PO5*B3IMAG
             B4REAL=(T4REAL+T6REAL)*SIN60
             B4IMAG=(T4IMAG+T6IMAG)*SIN60
             A(IADD1)   =T1REAL+B1REAL
             B(IADD1)   =T1IMAG+B1IMAG
             A(IADD1+IB)=T2REAL+B3REAL5+B4IMAG
             B(IADD1+IB)=T2IMAG+B3IMAG5-B4REAL
             A(IADD1+IC)=T1REAL-B1REAL5+B2IMAG
             B(IADD1+IC)=T1IMAG-B1IMAG5-B2REAL
             A(IADD1+ID)=T2REAL-B3REAL
             B(IADD1+ID)=T2IMAG-B3IMAG
             A(IADD1+IE)=T1REAL-B1REAL5-B2IMAG
             B(IADD1+IE)=T1IMAG-B1IMAG5+B2REAL
             A(IADD1+IF)=T2REAL+B3REAL5-B4IMAG
             B(IADD1+IF)=T2IMAG+B3IMAG5+B4REAL
           ENDDO
         ENDIF
       ELSEIF (NFFT .EQ. 5 ) THEN
C
C        FACTOR 5
C
         IC=IB+MSKIP
         ID=IC+MSKIP
         IE=ID+MSKIP
         IF(ISIGN.LT.0) THEN
           IADD1=-ISKIP2+1
*vdir nodep             
CDIR$ IVDEP
CDEC$ IVDEP
           DO NU=1,NUMBER
             IADD1=IADD1+ISKIP2
             T1REAL=A(IADD1+IB)+A(IADD1+IE)
             T1IMAG=B(IADD1+IB)+B(IADD1+IE)
             T2REAL=A(IADD1+IC)+A(IADD1+ID)
             T2IMAG=B(IADD1+IC)+B(IADD1+ID)
             T3REAL=A(IADD1+IB)-A(IADD1+IE)
             T3IMAG=B(IADD1+IB)-B(IADD1+IE)
             T4REAL=A(IADD1+IC)-A(IADD1+ID)
             T4IMAG=B(IADD1+IC)-B(IADD1+ID)
             T5REAL=T1REAL+T2REAL
             T5IMAG=T1IMAG+T2IMAG
             T6REAL=SQ54*(T1REAL-T2REAL)
             T6IMAG=SQ54*(T1IMAG-T2IMAG)
             T7REAL=A(IADD1)-T5REAL*PO25
             T7IMAG=B(IADD1)-T5IMAG*PO25
             T8REAL=T7REAL+T6REAL
             T8IMAG=T7IMAG+T6IMAG
             T9REAL=T7REAL-T6REAL
             T9IMAG=T7IMAG-T6IMAG
             T10REAL=SIN72*T3REAL+SIN36*T4REAL
             T10IMAG=SIN72*T3IMAG+SIN36*T4IMAG
             T11REAL=SIN36*T3REAL-SIN72*T4REAL
             T11IMAG=SIN36*T3IMAG-SIN72*T4IMAG
             A(IADD1)   =A(IADD1)+T5REAL
             B(IADD1)   =B(IADD1)+T5IMAG
             A(IADD1+IB)=T8REAL-T10IMAG
             B(IADD1+IB)=T8IMAG+T10REAL
             A(IADD1+IC)=T9REAL-T11IMAG
             B(IADD1+IC)=T9IMAG+T11REAL
             A(IADD1+ID)=T9REAL+T11IMAG
             B(IADD1+ID)=T9IMAG-T11REAL
             A(IADD1+IE)=T8REAL+T10IMAG
             B(IADD1+IE)=T8IMAG-T10REAL
           ENDDO
         ELSE
           IADD1=-ISKIP2+1
*vdir nodep             
CDIR$ IVDEP
CDEC$ IVDEP
           DO NU=1,NUMBER
             IADD1=IADD1+ISKIP2
             T1REAL=A(IADD1+IB)+A(IADD1+IE)
             T1IMAG=B(IADD1+IB)+B(IADD1+IE)
             T2REAL=A(IADD1+IC)+A(IADD1+ID)
             T2IMAG=B(IADD1+IC)+B(IADD1+ID)
             T3REAL=A(IADD1+IB)-A(IADD1+IE)
             T3IMAG=B(IADD1+IB)-B(IADD1+IE)
             T4REAL=A(IADD1+IC)-A(IADD1+ID)
             T4IMAG=B(IADD1+IC)-B(IADD1+ID)
             T5REAL=T1REAL+T2REAL
             T5IMAG=T1IMAG+T2IMAG
             T6REAL=SQ54*(T1REAL-T2REAL)
             T6IMAG=SQ54*(T1IMAG-T2IMAG)
             T7REAL=A(IADD1)-T5REAL*PO25
             T7IMAG=B(IADD1)-T5IMAG*PO25
             T8REAL=T7REAL+T6REAL
             T8IMAG=T7IMAG+T6IMAG
             T9REAL=T7REAL-T6REAL
             T9IMAG=T7IMAG-T6IMAG
             T10REAL=SIN72*T3REAL+SIN36*T4REAL
             T10IMAG=SIN72*T3IMAG+SIN36*T4IMAG
             T11REAL=SIN36*T3REAL-SIN72*T4REAL
             T11IMAG=SIN36*T3IMAG-SIN72*T4IMAG
             A(IADD1)   =A(IADD1)+T5REAL
             B(IADD1)   =B(IADD1)+T5IMAG
             A(IADD1+IB)=T8REAL+T10IMAG
             B(IADD1+IB)=T8IMAG-T10REAL
             A(IADD1+IC)=T9REAL+T11IMAG
             B(IADD1+IC)=T9IMAG-T11REAL
             A(IADD1+ID)=T9REAL-T11IMAG
             B(IADD1+ID)=T9IMAG+T11REAL
             A(IADD1+IE)=T8REAL-T10IMAG
             B(IADD1+IE)=T8IMAG+T10REAL
           ENDDO
         ENDIF
       ELSEIF (NFFT .EQ. 4) THEN
C
C        FACTOR 4 
C
         IC=IB+MSKIP
         ID=IC+MSKIP
         IF(ISIGN.LT.0) THEN
           IADD1=-ISKIP2+1
*vdir nodep             
CDIR$ IVDEP
CDEC$ IVDEP
           DO NU=1,NUMBER
             IADD1=IADD1+ISKIP2
             T1REAL=A(IADD1)+A(IADD1+IC)
             T1IMAG=B(IADD1)+B(IADD1+IC)
             T2REAL=A(IADD1+IB)+A(IADD1+ID)
             T2IMAG=B(IADD1+IB)+B(IADD1+ID)
             T3REAL=A(IADD1)-A(IADD1+IC)
             T3IMAG=B(IADD1)-B(IADD1+IC)
             T4REAL=A(IADD1+IB)-A(IADD1+ID)
             T4IMAG=B(IADD1+IB)-B(IADD1+ID)
             A(IADD1)   =T1REAL+T2REAL
             B(IADD1)   =T1IMAG+T2IMAG
             A(IADD1+IB)=T3REAL-T4IMAG
             B(IADD1+IB)=T3IMAG+T4REAL
             A(IADD1+IC)=T1REAL-T2REAL
             B(IADD1+IC)=T1IMAG-T2IMAG
             A(IADD1+ID)=T3REAL+T4IMAG
             B(IADD1+ID)=T3IMAG-T4REAL
           ENDDO
         ELSE
           IADD1=-ISKIP2+1
*vdir nodep             
CDIR$ IVDEP
CDEC$ IVDEP
           DO NU=1,NUMBER
             IADD1=IADD1+ISKIP2
             T1REAL=A(IADD1)+A(IADD1+IC)
             T1IMAG=B(IADD1)+B(IADD1+IC)
             T2REAL=A(IADD1+IB)+A(IADD1+ID)
             T2IMAG=B(IADD1+IB)+B(IADD1+ID)
             T3REAL=A(IADD1)-A(IADD1+IC)
             T3IMAG=B(IADD1)-B(IADD1+IC)
             T4REAL=A(IADD1+IB)-A(IADD1+ID)
             T4IMAG=B(IADD1+IB)-B(IADD1+ID)
             A(IADD1)   =T1REAL+T2REAL
             B(IADD1)   =T1IMAG+T2IMAG
             A(IADD1+IB)=T3REAL+T4IMAG
             B(IADD1+IB)=T3IMAG-T4REAL
             A(IADD1+IC)=T1REAL-T2REAL
             B(IADD1+IC)=T1IMAG-T2IMAG
             A(IADD1+ID)=T3REAL-T4IMAG
             B(IADD1+ID)=T3IMAG+T4REAL
           ENDDO
         ENDIF
       ELSEIF (NFFT .EQ. 3) THEN
C
C        FACTOR THREE 
C
         IC=IB+MSKIP
         IF(ISIGN.LT.0) THEN
           IADD1=-ISKIP2+1
*vdir nodep             
CDIR$ IVDEP
CDEC$ IVDEP
           DO NU=1,NUMBER
             IADD1=IADD1+ISKIP2
             T1REAL=A(IADD1+IB)+A(IADD1+IC)
             T1IMAG=B(IADD1+IB)+B(IADD1+IC)
             T2REAL=A(IADD1)-PO5*T1REAL
             T2IMAG=B(IADD1)-PO5*T1IMAG
             T3REAL=SIN60*(A(IADD1+IB)-A(IADD1+IC))
             T3IMAG=SIN60*(B(IADD1+IB)-B(IADD1+IC))
             A(IADD1)   =A(IADD1)+T1REAL
             B(IADD1)   =B(IADD1)+T1IMAG
             A(IADD1+IB)=T2REAL-T3IMAG
             B(IADD1+IB)=T2IMAG+T3REAL
             A(IADD1+IC)=T2REAL+T3IMAG
             B(IADD1+IC)=T2IMAG-T3REAL
           ENDDO
         ELSE
           IADD1=-ISKIP2+1
*vdir nodep             
CDIR$ IVDEP
CDEC$ IVDEP
           DO NU=1,NUMBER
             IADD1=IADD1+ISKIP2
             T1REAL=A(IADD1+IB)+A(IADD1+IC)
             T1IMAG=B(IADD1+IB)+B(IADD1+IC)
             T2REAL=A(IADD1)-PO5*T1REAL
             T2IMAG=B(IADD1)-PO5*T1IMAG
             T3REAL=SIN60*(A(IADD1+IB)-A(IADD1+IC))
             T3IMAG=SIN60*(B(IADD1+IB)-B(IADD1+IC))
             A(IADD1)   =A(IADD1)+T1REAL
             B(IADD1)   =B(IADD1)+T1IMAG
             A(IADD1+IB)=T2REAL+T3IMAG
             B(IADD1+IB)=T2IMAG-T3REAL
             A(IADD1+IC)=T2REAL-T3IMAG
             B(IADD1+IC)=T2IMAG+T3REAL
           ENDDO
         ENDIF
       ELSEIF (NFFT .EQ. 2) THEN
C
C        FACTOR TWO 
C
         IADD1=-ISKIP2+1
*vdir nodep             
CDIR$ IVDEP
CDEC$ IVDEP
         DO NU=1,NUMBER
           IADD1=IADD1+ISKIP2
           T1REAL=A(IADD1)-A(IADD1+IB)
           T1IMAG=B(IADD1)-B(IADD1+IB)
           A(IADD1)   =A(IADD1)+A(IADD1+IB)
           B(IADD1)   =B(IADD1)+B(IADD1+IB)
           A(IADD1+IB)=T1REAL
           B(IADD1+IB)=T1IMAG
         ENDDO
       ENDIF
       RETURN
       END
