      REAL*8 FUNCTION DDOT(N,SX,INCX,SY,INCY)
C
C     TRICKY WAY OF DEALING WITH SINGLE/DOUBLE PRECISION DEFINITIONS
C
C     FORMS THE DOT PRODUCT OF TWO VECTORS.
C     USES UNROLLED LOOPS FOR INCREMENTS EQUAL TO ONE.
C
      REAL*8 SX(1),SY(1),DDOT
      INTEGER INCX,INCY,N
      REAL*8 SDOT
      EXTERNAL SDOT
C
      DDOT = SDOT(N,SX,INCX,SY,INCY)
C
      RETURN
      END
