      LOGICAL FUNCTION LSAME ( CA, CB )
*     .. SCALAR ARGUMENTS ..
      CHARACTER*1            CA, CB
*     ..
*
*  PURPOSE
*  =======
*
*  LSAME  TESTS IF CA IS THE SAME LETTER AS CB REGARDLESS OF CASE.
*  CB IS ASSUMED TO BE AN UPPER CASE LETTER. LSAME RETURNS .TRUE. IF
*  CA IS EITHER THE SAME AS CB OR THE EQUIVALENT LOWER CASE LETTER.
*
*  N.B. THIS VERSION OF THE ROUTINE IS ONLY CORRECT FOR ASCII CODE.
*       INSTALLERS MUST MODIFY THE ROUTINE FOR OTHER CHARACTER-CODES.
*
*       FOR EBCDIC SYSTEMS THE CONSTANT IOFF MUST BE CHANGED TO -64.
*       FOR CDC SYSTEMS USING 6-12 BIT REPRESENTATIONS, THE SYSTEM-
*       SPECIFIC CODE IN COMMENTS MUST BE ACTIVATED.
*
*  PARAMETERS
*  ==========
*
*  CA     - CHARACTER*1
*  CB     - CHARACTER*1
*           ON ENTRY, CA AND CB SPECIFY CHARACTERS TO BE COMPARED.
*           UNCHANGED ON EXIT.
*
*
*  AUXILIARY ROUTINE FOR LEVEL 2 BLAS.
*
*  -- WRITTEN ON 20-JULY-1986
*     RICHARD HANSON, SANDIA NATIONAL LABS.
*     JEREMY DU CROZ, NAG CENTRAL OFFICE.
*
*     .. PARAMETERS ..
      INTEGER                IOFF
      PARAMETER            ( IOFF=32 )
*     .. INTRINSIC FUNCTIONS ..
      INTRINSIC              ICHAR
*     .. EXECUTABLE STATEMENTS ..
*
*     TEST IF THE CHARACTERS ARE EQUAL
*
      LSAME = CA .EQ. CB
*
*     NOW TEST FOR EQUIVALENCE
*
      IF ( .NOT.LSAME ) THEN
         LSAME = ICHAR(CA) - IOFF .EQ. ICHAR(CB)
      END IF
*
      RETURN
*
*  THE FOLLOWING COMMENTS CONTAIN CODE FOR CDC SYSTEMS USING 6-12 BIT
*  REPRESENTATIONS.
*
*     .. PARAMETERS ..
*     INTEGER                ICIRFX
*     PARAMETER            ( ICIRFX=62 )
*     .. SCALAR ARGUMENTS ..
*     CHARACTER*1            CB
*     .. ARRAY ARGUMENTS ..
*     CHARACTER*1            CA(*)
*     .. LOCAL SCALARS ..
*     INTEGER                IVAL
*     .. INTRINSIC FUNCTIONS ..
*     INTRINSIC              ICHAR, CHAR
*     .. EXECUTABLE STATEMENTS ..
*
*     SEE IF THE FIRST CHARACTER IN STRING CA EQUALS STRING CB.
*
*     LSAME = CA(1) .EQ. CB .AND. CA(1) .NE. CHAR(ICIRFX)
*
*     IF (LSAME) RETURN
*
*     THE CHARACTERS ARE NOT IDENTICAL. NOW CHECK THEM FOR EQUIVALENCE.
*     LOOK FOR THE 'ESCAPE' CHARACTER, CIRCUMFLEX, FOLLOWED BY THE
*     LETTER.
*
*     IVAL = ICHAR(CA(2))
*     IF (IVAL.GE.ICHAR('A') .AND. IVAL.LE.ICHAR('Z')) THEN
*        LSAME = CA(1) .EQ. CHAR(ICIRFX) .AND. CA(2) .EQ. CB
*     END IF
*
*     RETURN
*
*     END OF LSAME.
*
      END
