      SUBROUTINE XERBLA ( SRNAME, INFO )
*     ..    SCALAR ARGUMENTS ..
      INTEGER            INFO
      CHARACTER*6        SRNAME
*     ..
*
*  PURPOSE
*  =======
*
*  XERBLA  IS AN ERROR HANDLER FOR THE LEVEL 2 BLAS ROUTINES.
*
*  IT IS CALLED BY THE LEVEL 2 BLAS ROUTINES IF AN INPUT PARAMETER IS
*  INVALID.
*
*  INSTALLERS SHOULD CONSIDER MODIFYING THE STOP STATEMENT IN ORDER TO
*  CALL SYSTEM-SPECIFIC EXCEPTION-HANDLING FACILITIES.
*
*  PARAMETERS
*  ==========
*
*  SRNAME - CHARACTER*6.
*           ON ENTRY, SRNAME SPECIFIES THE NAME OF THE ROUTINE WHICH
*           CALLED XERBLA.
*
*  INFO   - INTEGER.
*           ON ENTRY, INFO SPECIFIES THE POSITION OF THE INVALID
*           PARAMETER IN THE PARAMETER-LIST OF THE CALLING ROUTINE.
*
*
*  AUXILIARY ROUTINE FOR LEVEL 2 BLAS.
*
*  WRITTEN ON 20-JULY-1986.
*
*     .. EXECUTABLE STATEMENTS ..
*
      WRITE (6,99999) SRNAME, INFO
*
      STOP
*
99999 FORMAT ( ' ** ON ENTRY TO ', A6, ' PARAMETER NUMBER ', I2,
     $         ' HAD AN ILLEGAL VALUE' )
*
*     END OF XERBLA.
*
      END
